import turtle
import time
time.time()
#start screen
wn = turtle.Screen()
wn.title("test")
wn.bgcolor("black")
wn.setup(width=600,height=600)
wn.tracer(0)
# labirinto mother fucker

person1 = turtle.Turtle()
person1.speed(0)
person1.shape("square")
person1.shapesize(stretch_wid=3,stretch_len=1)
person1.color("white")
person1.penup()
person1.goto(-260,290)

person2 = turtle.Turtle()
person2.speed(0)
person2.shape("square")
person2.shapesize(stretch_wid=1,stretch_len=3)
person2.color("white")
person2.penup()
person2.goto(-290,220)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-220,220)

person4 = turtle.Turtle()
person4.speed(0)
person4.shape("square")
person4.shapesize(stretch_wid=3,stretch_len=1)
person4.color("white")
person4.penup()
person4.goto(-200,250)


person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-115,270)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-180,270)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-50,270)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(15,270)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(80,270)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(145,270)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(215,270)


person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(230,220)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(230,155)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(265,80)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=4,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(220,50)


person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(147,80)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(170,20)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(105,20)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(40,20)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-25,20)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-90,20)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-220,20)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(-120,-20)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=5,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(-190,-40)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-155,-100)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-90,-100)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-25,-100)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(40,-100)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(105,-100)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(170,-100)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=2)
person3.color("white")
person3.penup()
person3.goto(225,-100)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(235,-145)
#ffghut
person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(-60,-60)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(75,-60)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(200,-60)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(5,-20)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(140,-20)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(260,-190)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(82,80)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(17,80)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-48,80)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-113,80)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-178,80)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=2)
person3.color("white")
person3.penup()
person3.goto(-230,80)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(-240,60)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(170,120)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(130,140)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(65,140)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(0,140)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-65,140)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-130,140)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.color("white")
person3.penup()
person3.goto(-195,140)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=2,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(-220,160)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("triangle")
person3.shapesize(stretch_wid=1,stretch_len=4)
person3.color("red")
person3.left(90)
person3.penup()
person3.goto(105,180)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("triangle")
person3.shapesize(stretch_wid=1,stretch_len=4)
person3.color("red")
person3.left(90)
person3.penup()
person3.goto(-20,170)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("triangle")
person3.shapesize(stretch_wid=1,stretch_len=4)
person3.left(90)
person3.color("red")
person3.penup()
person3.goto(-140,180)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("triangle")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.left(270)
person3.color("red")
person3.penup()
person3.goto(-80,250)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("triangle")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.left(270)
person3.color("red")
person3.penup()
person3.goto(40,250)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(-250,-140)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(-250,-205)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(-250,-270)


person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(-250,-140)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("square")
person3.shapesize(stretch_wid=3,stretch_len=1)
person3.color("white")
person3.penup()
person3.goto(-250,-140)



person3 = turtle.Turtle()
person3.speed(0)
person3.shape("triangle")
person3.shapesize(stretch_wid=1,stretch_len=3)
person3.left(90)
person3.color("yellow")
person3.penup()
person3.goto(-180,-270)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("triangle")
person3.shapesize(stretch_wid=1,stretch_len=7)
person3.left(90)
person3.color("yellow")
person3.penup()
person3.goto(-140,-270)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("triangle")
person3.shapesize(stretch_wid=1,stretch_len=9)
person3.left(90)
person3.color("yellow")
person3.penup()
person3.goto(-100,-270)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("triangle")
person3.shapesize(stretch_wid=1,stretch_len=6)
person3.left(90)
person3.color("yellow")
person3.penup()
person3.goto(-60,-270)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("triangle")
person3.shapesize(stretch_wid=1,stretch_len=4)
person3.left(90)
person3.color("yellow")
person3.penup()
person3.goto(-20,-270)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("triangle")
person3.shapesize(stretch_wid=1,stretch_len=11)
person3.left(90)
person3.color("yellow")
person3.penup()
person3.goto(40,-270)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("triangle")
person3.shapesize(stretch_wid=1,stretch_len=5)
person3.left(90)
person3.color("yellow")
person3.penup()
person3.goto(100,-270)

person3 = turtle.Turtle()
person3.speed(0)
person3.shape("triangle")
person3.shapesize(stretch_wid=1,stretch_len=10)
person3.left(90)
person3.color("yellow")
person3.penup()
person3.goto(140,-270)



#the small person
person0 = turtle.Turtle()
person0.speed(0)
person0.shape("turtle")
person0.shapesize(stretch_wid=0.8,stretch_len=0.8)
person0.color("orange")
person0.penup()
person0.goto(-290,290)


person9 = turtle.Turtle()
person9.speed(0)
person9.shape("square")
person9.shapesize(stretch_wid=1,stretch_len=1)
person9.color("blue")
person9.penup()
person9.goto(290,-290)


# up person
def up():
 a = person0.ycor()
 a +=20
 person0.sety(a)

#down person
def down():
 b = person0.ycor()
 b -=20
 person0.sety(b)
 
#left person
def left():
 c = person0.xcor()
 c -=20
 person0.setx(c)

#right person
def right():
 d = person0.xcor()
 d +=20
 person0.setx(d)


#functions of the keyboard 
wn.listen()
wn.onkeypress(up,"w")
wn.onkeypress(down,"s")
wn.onkeypress(left,"a")
wn.onkeypress(right,"d")

if (person0.xcor() and person0.ycor() == person9.ycor() and person9.xcor()):
  wn.clearscreen()
  wn.write("you win")

while True:
 wn.update()
 

